### ISSUE TITLE
git basic operations

### ISSUE THREAD

**Issue by maciej-adamiak** [maciej-adamiak/bigdata-fundamentals#4]
1. `init`
2. `add`: patterns, sequences
3. `commit`: inline message, edit message, `amend`
4. `checkout`: branching

**Comment by kalinka1304** [comment]
haha

**Comment by Lesna20** [comment]
buuu

**Comment by martanalej** [comment]
cześć

**Comment by Leszellek** [comment]
yyyy

**Comment by tomnap1979** [comment]
chyba ukradliście mi wszystkie pomysły
